# filebeat.inputs:
#   - type: log
#     paths:
#       - /var/app/log/*.log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false


output.elasticsearch:
  hosts: ["${ELASTIC_HOST}:${ELASTIC_PORT}"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

# output.console:
#   pretty: true

processors:
  - drop_fields:
      fields: ["ecs", "log", "input", "docker"]
      ignore_missing: true
  - decode_json_fields:
        fields: ["message"]
        process_array: false
        max_depth: 1
        target: "event"
        overwrite_keys: false
        add_error_key: true
  - drop_fields:
      fields: ["message"]
      ignore_missing: true
  - drop_event:
        when:
          not:
            has_fields: ["event.application"]